version: '3'

services:
  registry:
    image: registry:2
    container_name: docker-registry
    ports:
      - "5000:5000"
    environment:
       REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: '["http://your_ip:8080"]'
       REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '["GET","HEAD","OPTIONS"]'
       REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '["Accept","Authorization","Cache-Control"]'
       REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: '["true"]'
       REGISTRY_STORAGE_DELETE_ENABLED: 'true'

    volumes:
      - ./data:/var/lib/registry

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    ports:
      - "8080:80"
    environment:
      - REGISTRY_TITLE=My Docker Registry
      - REGISTRY_URL=http://your_ip:5000
    depends_on:
      - registry
